### ISSUE TITLE
Can't play 2 movies in parallel

### ISSUE THREAD

**Issue by Skroopa** [KDAB/android#4]
If I try to create two SurfaceTexture for playing two different movies I see only one texture:
<img src="https://i.stack.imgur.com/UnRkr.png">. 
Does it mean, that only one GL_TEXTURE_EXTERNAL_OES is possible?

**Comment by Skroopa** [comment]
1) you must place value for samplerExternalOES according to GL_TEXTURE0/1/2/... samplerExternalOES will be 0/1/2/... accordingly. not texture id.
2) placing glActiveTexture and glBindTexture in preprocess() is a bad idea. this params must be initiated in activate() (override) and deinitiated in deactivate (also override, through GL_TEXTURE0 and glBindTexture with zero value) or you will see artifacts with textures in QML.

**Comment by modricl** [comment]
@Skroopa Do you have any example how to do it?

**Comment by bog-dan-ro** [comment]
Fixed in  93bfbfe
