### ISSUE TITLE
[Help Wanted] Connect qsurfacetexture.cpp to Media Player "VideoOutput"

### ISSUE THREAD

**Issue by sk2212** [KDAB/android#5]
Hello Bogdan,

I am trying to connect your project with a Qml VLC wrapper component because there is an issue with 1080p content. It seems that the frames were not copied quick enough.
Playing the same video with your implementation is running smoothly.

I can connect the Qml Vlc Player implementation to QtMultimedia "Video Output" Qml component:

```
import QtMultimedia 5.6

VlcPlayer {
                id: vlcPlayer
}
```

```
VideoOutput {
            source: vlcPlayer
            anchors.fill: parent
}
```

The question is now:

Is it possible to connect your SurfaceTexture Qml component directly with VideoOutput to avoid changing the Qml Vlc Player implementation?

**Comment by bog-dan-ro** [comment]
I'm afraid it won't work, you need to check the implementation.
